### ISSUE TITLE
Unable to install from USB drive

### ISSUE THREAD

**Issue by JasperWeiss** [subgraph/subgraph-os-issues#143] opened 2016-05-02 10:32 UTC
Installing Subgraph from a USB drive (ISO written to USB flash drive using Rufus) makes the installer halt on detect and mount CD-ROM.

"Your installation media couldn't be mounted. This probably means the CD-ROM was not in the drive."

**Comment by nosmo** [comment] 2016-05-03 09:14
I've hit the same issue - you can work around this by dropping to a shell, umounting /media and mounting your install medium (whatever was mounted at /media) at /cdrom.

**Comment by JasperWeiss** [comment] 2016-05-03 09:31
Thanks, that worked. now I'll just have to wait for it to write my 750Gb drive full of data. (Seems pretty useless since I've always used FDE)

**Comment by xSmurf** [comment] 2016-05-31 17:59
Closing as fixed and duplicate of #144

**Closed by xSmurf** 2016-05-31 17:59 UTC

**Comment by bkerensa** [comment] 2016-07-25 06:29
This is still not fixed that or the fix isn't in the current iso. Would be nice if this were fixed in a published iso.

**Comment by bkerensa** [comment] 2016-07-26 04:42
@xSmurf ^

**Comment by jakubszajner** [comment] 2018-01-27 03:22
@xSmurf problem still exists...

**Comment by evil5hadow** [comment] 2018-02-21 21:54
Cannot install the OS.
I've used Rufus tool to write the ISO image to flash drive but the installed fails with "your installation cd-rom couldn't be mounted".
I've tried mount -t vfat /dev/sdb1 /cdrom but the installed failed again.

**Comment by binary1230** [comment] 2018-10-18 11:24
just a note for anyone else getting stuck here:
1) when creating the USB drive, if you use a tool like Rufus on windows to create a USB install from the .iso file, when prompted, you need to use 'DD' mode (not ISO mode which doesn't work).
2) boot up the installer
3) press ALT+F2, and enter to get to a shell
4) mount /dev/sdb1 /cdrom         [note: replace sdb1 with your usb drive]
5) proceed with the rest of the install
