### ISSUE TITLE
use snapshot.debian.org and/or provide snapshot repository to allow anyone building Subgraph OS

### ISSUE THREAD

**Issue by adrelanos** [subgraph/subgraph-os-issues#240] opened 2017-04-22 13:59 UTC
So far I failed to build Subgraph OS since it is [too difficult](https://secure-os.org/pipermail/desktops/2016-May/000116.html). David McKinney had agreed about a missing snapshot apt repository.

[Quote](https://secure-os.org/pipermail/desktops/2016-May/000124.html) David McKinney

> We're setting up our own repos that will allow us to stage stuff from testing and provide snapsnots. It will also make it easier to live-build Subgraph OS as the patched version can be obtained from our repository.

**Comment by mckinney-subgraph** [comment] 2017-04-22 14:52
This title is misleading. Subgraph OS can be built using `live-build` and our configuration (https://github.com/subgraph/subgraph_desktop_stretch). Anybody is already *allowed* to do it. We build Subgraph OS all of the time internally without a snapshot repo. 

If you are saying it is **too difficult** then you should provide specific information about what you have attempted to do with the `live-build` software. Perhaps we can help you with those specific technical concerns.

In regards to this statement:
>We're setting up our own repos that will allow us to stage stuff from testing and provide snapsnots. It >will also make it easier to live-build Subgraph OS as the patched version can be obtained from our >repository.

The `live-build` software is now being maintained and is available from the Debian repositories. At the time the statement was made, the future of that software was uncertain. We still do plan to set up our own repos that mirror testing and snapshot them according to our needs. `snapsnot.debian.org` does not figure into our plans.

We will have our own repos and snapshots at some point this year as a part of moving towards *beta* and eventually *1.0*.

**Comment by xSmurf** [comment] 2017-04-22 17:51
As pointed out, open tickets for specific issues detailing problems you have encountered. Submit PRs if you have fixes.

The actual ticket here: 

> use snapshot.debian.org and/or provide snapshot repository to allow anyone building Subgraph OS

is a duplicate of #85, specifics of the future repo infrastructure should go in there.

**Closed as completed by xSmurf** 2017-04-22 17:51 UTC
