### ISSUE TITLE
Cleanup Linux Packages

### ISSUE THREAD

**Issue by ghost** [subgraph/subgraph-os-issues#243] opened 2017-04-27 05:08 UTC
For some reason dist-upgrade is leaving old linux kernels which use up space and have to be manually removed

auto-remove also is not clearing them out

**Comment by DamirRT** [comment] 2017-04-27 05:53
Hi bkerensa,

 i have mentioned this in #155 

cheers

**Comment by xSmurf** [comment] 2017-04-27 14:42
I will close this as a dupe of #155, and upgrade the title of the former to be a little more specific :)

**Closed as completed by xSmurf** 2017-04-27 14:42 UTC
