### ISSUE TITLE
Unable to visit .onion sites

### ISSUE THREAD

**Issue by netgeak** [subgraph/subgraph-os-issues#207] opened 2017-01-31 04:45 UTC
I can browse https sites but not any .onion sites. I tried facebook, duckduckgo and various other onion sites. When I try I get connection has timed out. I verified the sites were accessible by downloading the tor browser to another machine and was able to reach them. 
Ive updated everything, not sure what else to do.
Thanks.

**Comment by dma** [comment] 2017-02-04 15:23
Are you still having this problem?

**Comment by netgeak** [comment] 2017-02-06 23:38
I tried updating and my networking got hosed. Related to case 209. Until I fix that or just do a fresh install theres no way to tell.

**Comment by neuralpancake** [comment] 2017-02-07 02:51
@netgeak: Added a note to #209   The wireless device is getting reconfigured as an ethernet device at the end of the upgrade process.  I just did a fresh install/update/upgrade to confirm this.

**Comment by dma** [comment] 2017-02-07 16:53
Can't reproduce this (didn't expect to) -- works fine for me. I'm using Tor Browser in Oz (sandboxed).

**Comment by neuralpancake** [comment] 2017-02-07 18:07
@dma: I suspect what netgeak is experiencing is solely related to #209.  .onion works w/ fresh install. Maybe close this and point to #209?

**Comment by netgeak** [comment] 2017-02-07 22:43
The issue occurred prior to updating and having the network reconfigured. I will do a fresh install, if the issue occurs again I will update this case.
Thanks.

**Comment by xSmurf** [comment] 2017-02-26 16:34
No updates, I'll close this ticket for now. Feel free to re-open if needed.

**Closed as completed by xSmurf** 2017-02-26 16:34 UTC
