### ISSUE TITLE
wifi mac address not randomizing

### ISSUE THREAD

**Issue by ioerror** [subgraph/subgraph-os-issues#128] opened 2016-04-01 16:06 UTC
My mac address doesn't randomize when joining wifi networks - I'm not sure why but when debugging a kernel crash, I noticed my actual mac address was in the captures. NetworkManager can change it if I manually set a mac address in the gnome ux for the specific wifi network.

**Comment by xSmurf** [comment] 2016-04-01 16:20
Confirmed, I just hit this as well. Somehow the udev script did not trigger!

**Comment by mckinney-subgraph** [comment] 2016-04-05 15:17
Possible causes:

* https://github.com/subgraph/macouflage/issues/1 (fixed, will publish a new package today)

See the issue notes to test.

* Affected interface is up before udev service is started -- this will mostly likely occur on VMs that either prohibit changing of MAC address or where the interface is "always on". I am not sure if it could happen on real hardware but it is worth looking at. 

You will find the following in `/var/log/syslog` in this case:
```
wlp1s0 interface is still up, cannot set MAC
```

* udev script not triggering as @xSmurf suggests. 

To detect this, udev will need to be setup for debugging.

See: https://wiki.ubuntu.com/DebuggingUdev

In particular:
```
To get more debug info from udev,

edit /usr/share/initramfs-tools/scripts/init-top/udev, and change the line starting udev by adding --debug, removing --daemon (using & instead), and sending stdout and stderr into a file called /dev/.udev.debug . 

For instance:

        /sbin/udevd --debug --resolve-names=never > /dev/.udev.debug 2>&1 & 
    then run sudo update-initramfs -k all -u
    After reboot, /dev/.udev.debug will have the udev debug info. 
```

**Comment by ioerror** [comment] 2016-04-05 15:54
This happened to me on an x220 with the non-free bios. It happens at
every boot. Just to confirm: it is possible change it with
NetworkManager's config on a per network basis.

**Comment by xSmurf** [comment] 2016-04-07 15:45
After investigation this is happening because of a regression in NetworkManager which somehow resets the interface on connection and does not carry over the changed MAC address.

https://bugzilla.gnome.org/show_bug.cgi?id=708820

We are looking at different ways of addressing this, most probably with a kernel patch.

**Comment by bkerensa** [comment] 2016-09-14 06:47
@xSmurf any ETA on when a new solution might be available in a Alpha?

**Comment by xSmurf** [comment] 2016-09-14 14:55
Upstream claims to have fixed it (Network Manager team has made such claims before, twice), and if that is the case that should land in stretch shortly. No precise time frame, but shortly.

**Comment by xSmurf** [comment] 2017-01-05 20:10
Finally fixed in the latest image/updates! :tada:

**Closed by xSmurf** 2017-01-05 20:10 UTC
Labels: bug
