### ISSUE TITLE
tor like an option

### ISSUE THREAD

**Issue by subproc** [subgraph/subgraph-os-issues#169] opened 2016-07-30 19:53 UTC
what about if a user can select if she/he wants to route all the traffic through the tor network or simply use an hardened debian base with an "unsecure" browser but with seccomp, pax, grsec, oz, etc...?

**Comment by xSmurf** [comment] 2016-08-26 21:27
Duplicate of #120, meanwhile #89 may be of help.

**Closed by xSmurf** 2016-08-26 21:27 UTC
