### ISSUE TITLE
xpra clipboard loop

### ISSUE THREAD

**Issue by ghost** [subgraph/subgraph-os-issues#81] opened 2016-02-09 23:43 UTC
when trying to use keepassx to fetch login credentials to access my email, my clipboard was disabled.
it wasn't the first time this has happened but it was the second time that it'd happened within an hour or so of use.
The following appears in the oz-daemon logs, which looks to show some kind of conflict between keepassx's use of the clipboard and xpra's handling of it

```
Feb  9 xx:xx:xx subgraph oz-daemon[851]: 2016/02/09 xx:xx:xx [torbrowser-launcher] (xpra) 2016-02-09 xx:xx:xx,xxx loop nesting too deep: 10
Feb  9 xx:xx:xx subgraph oz-daemon[851]: 2016/02/09 xx:xx:xx [torbrowser-launcher] (xpra) 2016-02-09 xx:xx:xx,xxx you may have a clipboard forwarding loop, disabling the clipboard
Feb  9 xx:xx:xx subgraph oz-daemon[851]: 2016/02/09 xx:xx:xx (xpra-stderr) 2016-02-09 xx:xx:xx,xxx clipboard toggled to off by the server, reason: probable clipboard loop detected
```

Looking back, there are other incidents, this is probably the one that happened previously.

```
Feb  9 xx:xx:xx subgraph oz-daemon[851]: 2016/02/09 xx:xx:xx [torbrowser-launcher] (xpra) 2016-02-09 xx:xx:xx,xxx clipboard disabled: more than 20 clipboard requests per second!
Feb  9 xx:xx:xx subgraph oz-daemon[851]: 2016/02/09 xx:xx:xx (xpra-stderr) 2016-02-09 xx:xx:xx,xxx clipboard toggled to off by the server, reason: more than 20 clipboard requests per second!
```

**Comment by xSmurf** [comment] 2016-02-10 17:59
Duplicate of https://github.com/subgraph/oz/issues/26

**Comment by xSmurf** [comment] 2016-03-20 22:41
I've upped the Xpra "clipboard limit" environment variable so this should be less common.

I've also added the `relaunchxpra` command to the oz client which allows restarting the xpra client without restarting the sandbox which can allow to mitigate this issue.

Keeping the ticket open, with a low priority, for further tracking of this issue.

**Comment by bnvk** [comment] 2016-10-12 13:01
I don't know if this is the correct issue or if subgraph/oz#26 is but I definitely experience a lot of  clipboard issues between apps that exist in sandboxes and non-sandboxed apps. The `oz relaunchxpra <ID>` trick works sometimes. But long running sandboxed apps tend to need to be fully restarted!

**Comment by dma** [comment] 2017-08-30 18:20
Fixed by https://github.com/subgraph/oz/commit/320ed99b57fd552273876285c5a3f8686259ef9e.

**Closed by dma** 2017-08-30 18:20 UTC
Labels: bug
