### ISSUE TITLE
TorBrowser path in paxrat_tbl.conf is specific to en_US localization

### ISSUE THREAD

**Issue by dma** [subgraph/subgraph-os-issues#139] opened 2016-04-09 21:13 UTC
Due to imperialism, istalling SGOS in another localization will result in the required pax flags never being set on the firefox binary.

One proposed fix is to include globbing in paxrat.

**Comment by xSmurf** [comment] 2016-04-10 16:18
Duplicate of #58

**Closed by xSmurf** 2016-04-10 16:18 UTC
